apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: ram-azu-qc1
  project: defaultproject
spec:
  blueprintConfig:
    name: ram-bp-opa-rctl-v3-spec-5th-july
    version: v2-311-opa-ui-4th-aug
  cloudCredentials: kalyan-azure
  config:
    kind: aksClusterConfig
    metadata:
      name: ram-azu-qc1
    spec:
      managedCluster:
        apiVersion: "2022-07-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: false
          dnsPrefix: ram-azu-qc1-dns
          kubernetesVersion: 1.26.3
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
        sku:
          name: Basic
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2022-07-01"
        location: centralindia
        name: primary
        properties:
          count: 1
          enableAutoScaling: true
          maxCount: 1
          maxPods: 110
          minCount: 1
          mode: System
          orchestratorVersion: 1.26.3
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B2ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: ram-rg1
  proxyConfig: {}
  type: aks
