apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: varun-127-eks-4
  project: defaultproject
spec:
  blueprintConfig:
    name: varun-costmg
    version: v2
  cloudCredentials: varun-eks
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    managedNodeGroups:
    - amiFamily: Ubuntu2004
      desiredCapacity: 3
      instanceTypes:
      - t3.xlarge
      maxSize: 3
      minSize: 3
      name: ng-f965bed1
      version: "1.27"
      volumeSize: 80
      volumeType: gp3
    - amiFamily: Ubuntu2004
      desiredCapacity: 2
      instanceTypes:
      - t3.xlarge
      maxSize: 2
      minSize: 2
      name: ng-9f90706a
      tags:
        email: varun.chandrashekar@rafay.co
        env: qa
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: varun-127-eks-4
      region: us-west-2
      tags:
        email: varun.chandrashekar@rafay.co
        env: qa
      version: "1.27"
    network:
      cni:
        name: Calico-v3.24.5
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
