apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: varun-127-eks
  project: defaultproject
spec:
  blueprintConfig:
    name: varun-servicemesh-networkpolicy
    version: v1
  cloudCredentials: varun-eks
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      instanceTypes:
      - t3.medium
      maxSize: 2
      minSize: 2
      name: ng-0ae1bc28
      version: "1.27"
      volumeSize: 80
      volumeType: gp3
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      instanceTypes:
      - t3.xlarge
      maxSize: 2
      minSize: 1
      name: ng-56419db3
      tags:
        email: varun.c@rafay.co
        env: qa
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: varun-127-eks
      region: us-west-2
      tags:
        email: varun.c@rafay.co
        env: qa
      version: "1.27"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
