apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: varun-127-eks-3
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
    version: Latest
  cloudCredentials: varun-eks
  config:
    managedNodeGroups:
    - amiFamily: Ubuntu2004
      desiredCapacity: 3
      instanceTypes:
      - t3.xlarge
      maxSize: 3
      minSize: 3
      name: ng-b8e2b669
      version: "1.25"
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: varun-127-eks-3
      region: us-west-2
      tags:
        email: varun.chandrashekar@rafay.co
        env: qa
      version: "1.25"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
